### ISSUE TITLE
输入/mj 后无法正常画图，求大佬帮忙解决

### ISSUE THREAD

**Issue by TGap-Ruo** [mouxangithub/plugin_midjourney#22]
报错信息如下
`[ERROR][2023-08-08 13:41:41][mjapi.py:61] - 'code'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/plugins/midjourney-proxy-on-wechat/mjapi.py", line 59, in imagine
    return self.subTip(res)
           ^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/plugins/midjourney-proxy-on-wechat/mjapi.py", line 36, in subTip
    code = rj["code"]
           ~~^^^^^^^^
KeyError: 'code'
[INFO][2023-08-08 13:41:41][wechat_channel.py:189] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
❌ 任务提交失败), receiver=@096846fccff003ca0997665904846baaf168f18eaf61a7dd1c787b754cb53251
`
midjourney-proxy使用Zeabur部署，环境变量已部署（已验证midjourney-proxy正常）

**Comment by TGap-Ruo** [comment]
已解决，错误原因是域名后忘记加/mj了
