### ISSUE TITLE
请教一个问题，我全部都部署完了，也help成功，但是一直任务提交失败是什么原因昂？

### ISSUE THREAD

**Issue by iceiccy** [mouxangithub/plugin_midjourney#27]
作者大大，我想请教一下，我cow和[midjourney-proxy全部都部署完了，在微信里，各种help也都成功返回帮助，但是只要一提交任务，就反馈失败，代码为：[INFO][2023-09-13 23:51:04][midjourney.py:841] - [MJ] /imagine prompt=汽车 imgList=[]
[ERROR][2023-09-13 23:52:26][mjapi.py:62] - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Kevin\Cow\plugins\midjourney\mjapi.py", line 60, in imagine
    return self.subTip(res)
           ^^^^^^^^^^^^^^^^
  File "C:\Kevin\Cow\plugins\midjourney\mjapi.py", line 34, in subTip
    rj = res.json()
         ^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[INFO][2023-09-13 23:52:26][wechat_channel.py:189] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
❌ 任务提交失败), receiver=@4ffe62badde2a9871e75fd65cdd80af60ca631b1a49d78cd8d9db7c2fa061420
请问我这是哪儿出了问题？您可以给我一个联系方式么？如果方便的话，我不会乱打扰你的...感谢，感激不尽

**Comment by mouxangithub** [comment]
midjourney-proxy服务没起来或者域名ip配得不对

**Comment by iceiccy** [comment]
啊啊啊.对，好像就是"mj_api_secret": "",
"discordapp_proxy": "",这俩填写的不对，但是我实在不知道去哪儿获取，搜索+AI我都找不到，教程里也没有，我弄了三天了，快哭了，大佬，你有联系方式么？我能请教你一下么？感激不尽
